<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Montserrat:wght@600;700;800&family=Bebas+Neue&display=swap" rel="stylesheet" />
<script>
  tailwind.config = {
    darkMode: 'class',
    theme: {
      extend: {
        colors: {
          'on-primary-container': '#7584a2',
          'on-tertiary': '#ffffff',
          'tertiary-fixed-dim': '#efc13e',
          error: '#ba1a1a',
          'secondary-fixed-dim': '#41e279',
          'inverse-surface': '#2d3133',
          'on-primary': '#ffffff',
          secondary: '#006d32',
          'secondary-fixed': '#64ff92',
          'on-error': '#ffffff',
          'primary-container': '#0b1c34',
          'on-background': '#191c1e',
          'surface-container-low': '#f2f4f6',
          'surface-tint': '#505f7a',
          'surface-container-high': '#e6e8ea',
          'surface-container-highest': '#e0e3e5',
          'on-secondary': '#ffffff',
          tertiary: '#000000',
          'on-primary-fixed': '#0b1c34',
          primary: '#0b1c34',
          'on-error-container': '#93000a',
          'on-surface-variant': '#44474d',
          outline: '#75777e',
          'surface-container': '#eceef0',
          'on-tertiary-fixed-variant': '#594400',
          'tertiary-container': '#241a00',
          'on-tertiary-container': '#a47f00',
          'surface-bright': '#f7f9fb',
          surface: '#f7f9fb',
          'on-surface': '#191c1e',
          'on-secondary-container': '#007436',
          'on-primary-fixed-variant': '#384761',
          'inverse-primary': '#b7c7e7',
          'inverse-on-surface': '#eff1f3',
          'on-secondary-fixed': '#00210b',
          'tertiary-fixed': '#ffdf94',
          'error-container': '#ffdad6',
          'on-tertiary-fixed': '#241a00',
          'secondary-container': '#64ff92',
          'surface-container-lowest': '#ffffff',
          background: '#f7f9fb',
          'on-secondary-fixed-variant': '#005224',
          'surface-dim': '#d8dadc',
          'primary-fixed': '#d6e3ff',
          'surface-variant': '#e0e3e5',
          'primary-fixed-dim': '#b7c7e7',
          'outline-variant': '#c5c6ce',
          navy: '#0b1c34',
          'performance-green': '#006d32',
          'pb-navy': '#0b1c34',
          'pb-green': '#006d32',
          'pb-green-bright': '#17c964',
          'pb-gold': '#f4c542',
          'pb-bg': '#f7f9fb',
        },
        borderRadius: {
          DEFAULT: '0.25rem',
          lg: '0.5rem',
          xl: '0.75rem',
          '2xl': '1.125rem',
          brand: '1rem',
          full: '9999px',
        },
        spacing: {
          'margin-mobile': '16px',
          'element-gap': '24px',
          'section-gap': '80px',
          'container-max': '1280px',
          gutter: '24px',
          'margin-desktop': '48px',
        },
        fontFamily: {
          'display-hero': ['Montserrat', 'sans-serif'],
          'headline-md': ['Montserrat', 'sans-serif'],
          'headline-lg': ['Montserrat', 'sans-serif'],
          'headline-lg-mobile': ['Montserrat', 'sans-serif'],
          'body-md': ['Inter', 'sans-serif'],
          'body-lg': ['Inter', 'sans-serif'],
          'label-caps': ['Inter', 'sans-serif'],
          'stat-xl': ['"Bebas Neue"', 'sans-serif'],
          'stat-md': ['"Bebas Neue"', 'sans-serif'],
          display: ['Montserrat', 'sans-serif'],
          body: ['Inter', 'sans-serif'],
          stat: ['"Bebas Neue"', 'sans-serif'],
        },
        fontSize: {
          'stat-xl': ['56px', { lineHeight: '56px', letterSpacing: '0.05em', fontWeight: '400' }],
          'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '800' }],
          'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
          'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
          'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '800' }],
          'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
          'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
          'stat-md': ['32px', { lineHeight: '32px', letterSpacing: '0.03em', fontWeight: '400' }],
          'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '800' }],
        },
        maxWidth: {
          'container-max': '1280px',
          container: '1280px',
        },
      },
    },
  };
</script>
@include('partials.powerblink.theme-styles')
