<script>
  tailwind.config = {
    darkMode: 'class',
    theme: {
      extend: {
        colors: {
          'on-primary-container': '#7584a2',
          'on-tertiary': '#ffffff',
          'tertiary-fixed-dim': '#efc13e',
          error: '#ba1a1a',
          'secondary-fixed-dim': '#41e279',
          'inverse-surface': '#2d3133',
          'on-primary': '#ffffff',
          secondary: '#006d32',
          'secondary-fixed': '#64ff92',
          'on-error': '#ffffff',
          'primary-container': '#0b1c34',
          'on-background': '#191c1e',
          'surface-container-low': '#f2f4f6',
          'surface-tint': '#505f7a',
          'surface-container-high': '#e6e8ea',
          'surface-container-highest': '#e0e3e5',
          'on-secondary': '#ffffff',
          tertiary: '#000000',
          'on-primary-fixed': '#0b1c34',
          primary: '#0b1c34',
          'on-error-container': '#93000a',
          'on-surface-variant': '#44474d',
          outline: '#75777e',
          'surface-container': '#eceef0',
          'on-tertiary-fixed-variant': '#594400',
          'tertiary-container': '#241a00',
          'on-tertiary-container': '#a47f00',
          'surface-bright': '#f7f9fb',
          surface: '#f7f9fb',
          'on-surface': '#191c1e',
          'on-secondary-container': '#007436',
          'on-primary-fixed-variant': '#384761',
          'inverse-primary': '#b7c7e7',
          'inverse-on-surface': '#eff1f3',
          'on-secondary-fixed': '#00210b',
          'tertiary-fixed': '#ffdf94',
          'error-container': '#ffdad6',
          'on-tertiary-fixed': '#241a00',
          'secondary-container': '#64ff92',
          'surface-container-lowest': '#ffffff',
          background: '#f7f9fb',
          'on-secondary-fixed-variant': '#005224',
          'surface-dim': '#d8dadc',
          'primary-fixed': '#d6e3ff',
          'surface-variant': '#e0e3e5',
          'primary-fixed-dim': '#b7c7e7',
          'outline-variant': '#c5c6ce',
          navy: '#0b1c34',
          'performance-green': '#006d32',
        },
        borderRadius: {
          DEFAULT: '0.25rem',
          lg: '0.5rem',
          xl: '0.75rem',
          '2xl': '1.125rem',
          full: '9999px',
        },
        spacing: {
          'margin-mobile': '16px',
          'element-gap': '24px',
          'section-gap': '80px',
          'container-max': '1280px',
          gutter: '24px',
          'margin-desktop': '48px',
        },
        fontFamily: {
          'display-hero': ['Montserrat', 'sans-serif'],
          'headline-md': ['Montserrat', 'sans-serif'],
          'headline-lg': ['Montserrat', 'sans-serif'],
          'headline-lg-mobile': ['Montserrat', 'sans-serif'],
          'body-md': ['Inter', 'sans-serif'],
          'body-lg': ['Inter', 'sans-serif'],
          'label-caps': ['Inter', 'sans-serif'],
          'stat-xl': ['Bebas Neue', 'sans-serif'],
          'stat-md': ['Bebas Neue', 'sans-serif'],
        },
        maxWidth: {
          'container-max': '1280px',
        },
      },
    },
  };
</script>
